name: Update README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1'
      - run: |
          go install github.com/muesli/markscribe@master
          markscribe ./templates/readme.md.tpl > README.md
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          commit_message: 'docs: Update generated README'
          branch: dev
          commit_user_name: jayzsh
          commit_user_email: 55305804+jayzsh@users.noreply.github.com
          commit_author: jayzsh <55305804+jayzsh@users.noreply.github.com>
